services:
  - type: web
    name: chatapp-frontend
    env: node
    buildCommand: cd Frontend && npm install && npm run build
    startCommand: cd Frontend && npm run preview
    envVars:
      - key: NODE_ENV
        value: development
    staticPublishPath: Frontend/dist
