services:
  - type: web
    name: chatapp-fullstack
    env: node
    buildCommand: |
      NODE_ENV=development npm install &&
      NODE_ENV=development npm install --prefix Frontend &&
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
