services:
  - type: web
    name: chatapp-fullstack
    env: node
    buildCommand: npm install --include=dev && npm install --prefix Frontend --production=false --include=dev && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
